---
# Build out entire environment

- name: Apply Common Configuration to all Appliances
  hosts: all
  connection: local
  roles:
    - role: start_config
      tags: ["start"]
    - role: add_network_ipv4
      tags: ["ipv4"]
      add_network_ipv4_label                : "1.1"
      add_network_ipv4_address              : "{{ ipv4_1_1_ip_address }}"
      add_network_ipv4_maskOrPrefix         : "{{ ipv4_1_1_ip_mask }}"
      add_network_ipv4_allowManagement      : True
      when: ipv4_1_1_ip_address is defined
    - role: set_network_ipv4_dhcp
      tags: ["dhcp"]
      set_network_ipv4_dhcp_label           : "1.1"
      set_network_ipv4_dhcp_allowManagement : False
      set_network_ipv4_dhcp_enabled         : False
      set_network_ipv4_dhcp_providesDefaultRoute: False
      when: ipv4_1_1_ip_address is defined
    - role: add_network_ipv4
      tags: ["ipv4"]
      add_network_ipv4_label                : "1.2"
      add_network_ipv4_address              : "{{ ipv4_1_2_ip_address }}"
      add_network_ipv4_maskOrPrefix         : "{{ ipv4_1_2_ip_mask }}"
      add_network_ipv4_allowManagement      : False
      when: ipv4_1_1_ip_address is defined
    - role: set_network_hostname
      tags: ["hostname"]
      set_network_hostname_hostname         : "{{ appliance_name }}"
    - role: config_dns
      tags: ["dns"]
    - role: config_ntp
      tags: ["ntp"]
    - role: config_snmp_monitoring
      tags: ["snmp"]
      config_snmp_monitoring_community: "ibm"
      config_snmp_monitoring_port: 161
    - role: activate_module
      tags: ["activate", "wga"]
      activate_module_id  : "wga"
      activate_module_code: "{{ lookup('file', '/home/python/ISAM_90_ACTIVATION_CODE_MP_ML.txt') }}"

- name: Setup Primary Appliance
  hosts: primary
  connection: local
  roles:
    - role: config_policyserver
      tags: ["policyserver", "config"]
      config_policyserver_admin_pwd: "{{sec_master_pwd}}"
      config_policyserver_ldap_pwd: "passw0rd"
    - role: set_cluster_config
      set_cluster_config_primary_master: "{{ ipv4_1_1_ip_address}}"
    - role: set_cert_replication
      tags: ["certificate", "replication"]
    - role: set_runtime_replication
      tags: ["runtime", "replication"]
    - role: export_cluster_sign
      export_cluster_sign_filename: "/home/python/primary.sign"

- name: Setup Restricted Appliances
  hosts: restricted
  connection: local
  vars:
    reverseproxy_instance_name: "default"
  roles:
    - role: add_cluster_node
      tags: ["cluster", "add"]
      add_cluster_node_signature_file: "/home/python/primary.sign"
      add_cluster_node_restricted:     True
    - role: set_tcpip_tuning
      tags: ["tcpip"]
    - role: create_reverseproxy
      tags: ["reverseproxy", "create"]
      create_reverseproxy_host      : "{{ appliance_name.split('.')[0] }}"
      create_reverseproxy_inst_name : "{{ reverseproxy_instance_name }}"
      create_reverseproxy_ip_address: "{{ ipv4_1_2_ip_address}}"
      create_reverseproxy_admin_id  : "{{ sec_master_id }}"
      create_reverseproxy_admin_pwd : "{{ sec_master_pwd }}"

- name: Setup Primary Appliance
  hosts: primary
  connection: local
  roles:
    - role: execute_pdadmin
      tags: ["pdadmin", "object", "create"]
      execute_pdadmin_commands:
        - "object create /WebSEAL/ibm \"Common Web Root for all Reverse Proxies\" 5 ispolicyattachable yes"
      execute_pdadmin_isamuser: "{{sec_master_id}}"
      execute_pdadmin_isampwd:  "{{sec_master_pwd}}"

- name: Setup Restricted Appliances
  hosts: restricted
  connection: local
  vars:
    reverseproxy_instance_name: "default"
  roles:
    - role: update_reverseproxy_conf
      tags: ["reverseproxy", "update"]
      update_reverseproxy_conf_reverseproxy_id: "{{ reverseproxy_instance_name }}"
      update_reverseproxy_conf_entries:
        - stanza_id: "server"
          entry_id:  "server-name"
          value_id:  "ibm"
