---
# Create
#   create api protection definitions
#   Example:
#     api_protection:
#       definitions:
#         - name: oauth-provider
#           description: API protection for Signal Iduna OAuth service provider
#           grantTypes:
#             - AUTHORIZATION_CODE
#           tcmBehavior: NEVER_PROMPT
- hosts: "{{ hosts | default('all')}}"
  connection: local
  roles:
    - role: aac/create_api_protection_definitions
      tags: create_api_protection_definitions
      