# playbook for creating certificate databases
# Example inventory:
#  create_certificate_databases:
#      kdb_id: "{{ item.kdb_id }}"
---
- hosts: "{{ hosts | default('all')}}"
  connection: local
  roles:
    - role: base/create_ssl_certificate_databases
      tags: create_ssl_certificate_databases