---
# Upload
#   upload signer certificates into certificate database
#   Example:
#      upload_signer_certificates:
#         -   kdb_id: "{{ item.kdb_id }}"
#             cert: "{{ inventory_dir }}/{{ item.cert  }}"
#             label: "{{ item.label }}"
- hosts: "{{ hosts | default('all')}}"
  connection: local
  roles:
    - role: base/upload_signer_certificates
      tags: upload_signer_certificates