---
# restart
#   restart reverse proxy instance/s
- hosts: "{{ hosts | default('all')}}"
  connection: local
  roles:
    - role: web/restart_reverseproxy_instance
      tags: restart_reverseproxy_instance
