---
# upload
#   upload runtime components
#   Example:
#     runtime_components:
#       - migrate_file: "{{ inventory_dir }}/uploads/runtime/ldap/ldap.conf"
- hosts: "{{ hosts | default('all')}}"
  connection: local
  roles:
    - role: web/upload_runtime_components
      tags: upload_runtime_components
